name: 'Rsync Deployer'
description: 'Deploy files using rsync over SSH with detailed statistics and backup options'
author: 'imajeetyadav'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  host:
    description: 'SSH host'
    required: true
  
  username:
    description: 'SSH username'
    required: true
  
  key:
    description: 'SSH private key'
    required: true
  
  port:
    description: 'SSH port'
    required: false
    default: '22'
  
  source_path:
    description: 'Source path'
    required: false
    default: '.'
  
  target_path:
    description: 'Target path on remote host'
    required: true
  
  exclude_list:
    description: 'List of files/directories to exclude (comma-separated)'
    required: false
    default: '.git/'
  
  rsync_parameters:
    description: 'Additional rsync parameters'
    required: false
  
  delete_option:
    description: 'Delete extraneous files from destination dirs'
    required: false
    default: 'false'
  
  backup_path:
    description: 'Backup directory path on remote host'
    required: false
  
  dry_run:
    description: 'Perform a trial run with no changes made'
    required: false
    default: 'false'
  
  print_summary:
    description: 'Print deployment summary'
    required: false
    default: 'true'
  
  print_statistics:
    description: 'Print deployment statistics'
    required: false
    default: 'true'
  
  print_rsync_logs:
    description: 'Print rsync logs during execution'
    required: false
    default: 'true'
  
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/imajeetyadav/rsync:2.0.0'
  env:
    INPUT_HOST: ${{ inputs.host }}
    INPUT_USERNAME: ${{ inputs.username }}
    INPUT_KEY: ${{ inputs.key }}
    INPUT_PORT: ${{ inputs.port }}
    INPUT_SOURCE_PATH: ${{ inputs.source_path }}
    INPUT_TARGET_PATH: ${{ inputs.target_path }}
    INPUT_EXCLUDE_LIST: ${{ inputs.exclude_list }}
    INPUT_RSYNC_PARAMETERS: ${{ inputs.rsync_parameters }}
    INPUT_DELETE_OPTION: ${{ inputs.delete_option }}
    INPUT_BACKUP_PATH: ${{ inputs.backup_path }}
    INPUT_DRY_RUN: ${{ inputs.dry_run }}
    INPUT_PRINT_SUMMARY: ${{ inputs.print_summary }}
    INPUT_PRINT_STATISTICS: ${{ inputs.print_statistics }}
    INPUT_PRINT_RSYNC_LOGS: ${{ inputs.print_rsync_logs }}
    INPUT_DEBUG: ${{ inputs.debug }}
